services:
    pikaron.searchback.listener:
        class: pikaron\searchback\event\listener
        arguments:
            - '@user'
            - '@template'
            - '@dbal.conn'
            - '@auth'
            - '@request'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    _defaults:
        public: true